name: Daily AutoApply

on:
  schedule:
    - cron: "30 0 * * *" # Runs at 12:30 AM UTC every day
  workflow_dispatch: # 👈 This enables manual trigger

jobs:
  auto-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Add random delay (0–45 minutes)
        run: sleep $(( RANDOM % 2700 ))

      - name: Run autoapply
        run: node main.js
        env:
          NODE_ENV: production
